variavel = input('Digite algo:')
print('O tipo primitico desse valor e', type(variavel))
print('So tem espaços?', variavel.isspace())
print('E um numero?', variavel.isnumeric())
print('E alfabetico?', variavel.isalpha())
print('E alfanumerico?', variavel.isalnum())
print('Esta em maiuscula?', variavel.isupper())
print('Esta em minuscula', variavel.islower())
print('Esta capitalizada?', variavel.istitle())
