nome = str(input('Qual e o seu nome completo?')).strip().title()
print('Analisando seu nome...')
print('Seu nome em maiusculo fica...{}'.format(nome.upper()))
print('Seu nome em minusculo fica...{}'.format(nome.lower()))
print('Seu nome tem um total de letras igual a...{}'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))